apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "karpenter.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
data:
  config.yaml: |
    settings:
      clusterName: {{ .Values.env[1].value }}
      interruptionHandling: true
