apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "karpenter.selectorLabels" . | nindent 4 }}
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
