{{- if .Values.rollout.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.rollout.replicas | default .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flask-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flask-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flask-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
            - name: FLASK_DEBUG
              value: {{ .Values.config.flaskDebug | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    canary:
      {{- if .Values.rollout.strategy.canary.analysis.enabled }}
      analysis:
        templates:
          {{- range .Values.rollout.strategy.canary.analysis.templates }}
          - templateName: {{ . }}
          {{- end }}
        args:
          - name: service-name
            value: {{ include "flask-app.fullname" . }}
        startingStep: {{ .Values.rollout.strategy.canary.analysis.startingStep }}
      {{- end }}
      steps:
        {{- toYaml .Values.rollout.strategy.canary.steps | nindent 8 }}
      trafficRouting:
        alb:
          ingress: {{ include "flask-app.fullname" . }}
          servicePort: 80
{{- end }}
