apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "5.51.6"
    helm:
      releaseName: argocd
      parameters:
        - name: server.service.type
          value: LoadBalancer
        - name: configs.cm.credentialTemplates.github.url
          value: https://github.com/dmitri166/EKS_project
        - name: configs.cm.credentialTemplates.github.username
          value: dmitri166
        - name: configs.cm.credentialTemplates.github.password
          value: $github.pat
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
