apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dmitri166/EKS_project.git
    targetRevision: master
    path: helm/karpenter
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: serviceAccount.annotations."eks\.amazonaws\.com/role-arn"
          value: "arn:aws:iam::025988852505:role/flask-devops-karpenter-controller"
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
